server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-product:5432/produtos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
